name: Express PR Actions
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1', '8.2']
    steps:
      - name: ğŸ‰ Triggered by ${{ github.event_name }}
        run: echo "This job was automatically triggered by a ${{ github.event_name }} event."

      - name: ğŸ§ Run on ${{ runner.os }}
        run: echo "This job is running on a ${{ runner.os }} server hosted by GitHub!"

      - name: ğŸ” Branch and Repository Information
        run: |
          echo "The name of your branch is ${{ github.ref }}"
          echo "Your repository is ${{ github.repository }}"

      - name: ğŸ› ï¸ Check out repository code
        uses: actions/checkout@v4

      - name: ğŸ˜ Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: intl # Add any necessary PHP extensions

      - name: ğŸš¨ Check PHP Linting
        run: php -l .

      - name: ğŸš¦ Check Code Style
        run: vendor/bin/phpcs
